version: '3.8'

services:
  # FastAPI Application
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: supervisor-workers-web
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=chatbot
    volumes:
      - ./app:/app/app
      - ./templates:/app/templates
      - ./static:/app/static
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: unless-stopped
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # MongoDB Service
  mongodb:
    image: mongo:7.0
    container_name: supervisor-workers-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=chatbot
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/chatbot --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # Mongo Express (Optional - MongoDB Web UI)
  mongo-express:
    image: mongo-express:latest
    container_name: supervisor-workers-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017/
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
